openapi: 3.0.3
info:
  title: FastAPI
  version: 1.0.0
paths:
  /health/livez:
    get:
      operationId: get_livez_health_livez_get
      summary: Live health check
      description: Check the health of the service.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessResponse'
      tags:
        - health
  /health/readyz:
    get:
      operationId: get_readyz_health_readyz_get
      summary: Ready health check
      description: Check if the service is ready to process requests.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadinessResponse'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - health
  /health/status:
    get:
      operationId: get_status_health_status_get
      summary: Service stats endpoint
      description: Check basic service details.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
      tags:
        - health
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: string
          title: Data
        status:
          type: string
          enum:
            - ERROR
          title: Status
      required:
        - data
        - status
      title: ErrorResponse
    LivenessResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - OK
          title: Status
      required:
        - status
      title: LivenessResponse
    ReadinessResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: string
          title: Data
        status:
          type: string
          enum:
            - OK
          title: Status
      required:
        - data
        - status
      title: ReadinessResponse
    StatusResponse:
      type: object
      properties:
        name:
          type: string
          title: Name
        version:
          type: string
          title: Version
      required:
        - name
        - version
      title: StatusResponse
