openapi: 3.0.3
info:
  title: Configuration Api
  description: Nice description goes here
  termsOfService: http://we.dont.care.yet.com/term-of-service
  contact:
    name: We need a person
    url: http://we.dont.care.yet.com/contact
    email: support@capenetworks.com
  license:
    name: No idea, but we need something
  version: 1.5.0
servers:
  - url: https://api.capenetworks.com
  - url: https://api.staging.capedev.io
paths:
  /health/livez:
    get:
      operationId: get_livez_health_livez_get
      summary: Live health check
      description: Check the health of the service.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessResponse'
      deprecated: true
      tags:
        - health
  /health/readyz:
    get:
      operationId: get_readyz_health_readyz_get
      summary: Ready health check
      description: Check if the service is ready to process requests.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadinessResponse'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadinessErrorResponse'
      deprecated: true
      tags:
        - health
  /health/status:
    get:
      operationId: get_status_health_status_get
      summary: Service stats endpoint
      description: Check basic service details.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
      deprecated: true
      tags:
        - health
  /configuration/app/v1/groups:
    get:
      operationId: groups_get_configuration_app_v1_groups_get
      summary: Groups Get
      description: Lists groups matching provided criteria
      parameters:
        - name: uid
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Uid
        - name: cursor
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Cursor
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsGetResponse'
        4XX:
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - HTTPBearer: []
      tags:
        - api
        - configuration
        - v1
        - groups
    post:
      operationId: groups_post_configuration_app_v1_groups_post
      summary: Groups Post
      description: >-
        Create a new group with the group identified in `parent_uid` as its parent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupsPostRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsPostResponse'
        4XX:
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - HTTPBearer: []
      tags:
        - api
        - configuration
        - v1
        - groups
  /configuration/app/v1/sensor-group-assignments:
    get:
      operationId: get_configuration_app_v1_sensor_group_assignments_get
      summary: Get
      description: Get a list of sensor group assignments
      parameters:
        - name: uid
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Uid
        - name: cursor
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Cursor
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorGroupAssignmentsResponse'
        4XX:
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - HTTPBearer: []
      tags:
        - api
        - configuration
        - v1
        - sensor-group-assignments
      x-stability-level: alpha
components:
  schemas:
    ErrorDetail:
      type: object
      properties:
        message:
          type: string
          title: Message
      required:
        - message
      title: ErrorDetail
    ErrorResponse:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
          title: Detail
      required:
        - detail
      title: ErrorResponse
    GroupsGetItem:
      type: object
      properties:
        uid:
          type: string
          title: Uid
        name:
          type: string
          title: Name
        path:
          type: string
          title: Path
        parent_uid:
          type: string
          title: Parent Uid
      required:
        - uid
        - name
        - path
        - parent_uid
      title: GroupsGetItem
    GroupsGetResponse:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
        groups:
          type: array
          items:
            $ref: '#/components/schemas/GroupsGetItem'
          title: Groups
      required:
        - pagination
        - groups
      title: GroupsGetResponse
    GroupsPostRequest:
      type: object
      properties:
        parent_uid:
          type: string
          title: Parent Uid
        name:
          type: string
          title: Name
      required:
        - parent_uid
        - name
      title: GroupsPostRequest
    GroupsPostResponse:
      type: object
      properties:
        parent_uid:
          type: string
          title: Parent Uid
        name:
          type: string
          title: Name
        uid:
          type: string
          title: Uid
        path:
          type: string
          title: Path
      required:
        - parent_uid
        - name
        - uid
        - path
      title: GroupsPostResponse
    LivenessResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - OK
          title: Status
      required:
        - status
      title: LivenessResponse
    PaginationDetails:
      type: object
      properties:
        limit:
          type: integer
          title: Limit
        next:
          anyOf:
            - type: string
          nullable: true
          title: Next
        previous:
          anyOf:
            - type: string
          nullable: true
          title: Previous
        first:
          anyOf:
            - type: string
          nullable: true
          title: First
        last:
          anyOf:
            - type: string
          nullable: true
          title: Last
      required:
        - limit
        - next
        - previous
        - first
        - last
      title: PaginationDetails
    ReadinessErrorResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: string
          title: Data
        status:
          type: string
          enum:
            - ERROR
          title: Status
      required:
        - data
        - status
      title: ReadinessErrorResponse
    ReadinessResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: string
          title: Data
        status:
          type: string
          enum:
            - OK
          title: Status
      required:
        - data
        - status
      title: ReadinessResponse
    SensorGroupAssignment:
      type: object
      properties:
        uid:
          type: string
          title: Uid
        group_uid:
          type: string
          title: Group Uid
        sensor_uid:
          type: string
          title: Sensor Uid
      required:
        - uid
        - group_uid
        - sensor_uid
      title: SensorGroupAssignment
    SensorGroupAssignmentsResponse:
      type: object
      properties:
        sensor_group_assignments:
          type: array
          items:
            $ref: '#/components/schemas/SensorGroupAssignment'
          title: Sensor Group Assignments
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
      required:
        - sensor_group_assignments
        - pagination
      title: SensorGroupAssignmentsResponse
    StatusResponse:
      type: object
      properties:
        name:
          type: string
          title: Name
        version:
          type: string
          title: Version
      required:
        - name
        - version
      title: StatusResponse
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
tags:
  - name: api
  - name: v1
  - name: configuration
  - name: groups
  - name: health
  - name: sensor-group-assignments
