openapi: 3.0.3
info:
  title: Configuration Api
  description: Nice description goes here
  termsOfService: http://we.dont.care.yet.com/term-of-service
  contact:
    name: We need a person
    url: http://we.dont.care.yet.com/contact
    email: support@capenetworks.com
  license:
    name: No idea, but we need something
  version: 1.9.0
servers:
  - url: https://api.capenetworks.com
  - url: https://api.staging.capedev.io
paths:
  /configuration/app/v1/groups:
    get:
      operationId: groups_get_configuration_app_v1_groups_get
      summary: Groups Get
      description: Lists groups matching provided criteria
      parameters:
        - name: uid
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Uid
        - name: cursor
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Cursor
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsGetResponse'
        4XX:
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - HTTPBearer: []
      tags:
        - api
        - configuration
        - v1
        - groups
      x-stability-level: alpha
    post:
      operationId: groups_post_configuration_app_v1_groups_post
      summary: Groups Post
      description: >-
        Create a new group with the group identified in `parent_uid` as its
        parent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupsPostRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsPostResponse'
        4XX:
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - HTTPBearer: []
      tags:
        - api
        - configuration
        - v1
        - groups
  /configuration/app/v1/sensor-group-assignments:
    get:
      operationId: get_configuration_app_v1_sensor_group_assignments_get
      summary: Get
      description: Get a list of sensor group assignments
      parameters:
        - name: uid
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Uid
        - name: cursor
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Cursor
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorGroupAssignmentsResponse'
        4XX:
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - HTTPBearer: []
      tags:
        - api
        - configuration
        - v1
        - sensor-group-assignments
      x-stability-level: alpha
  /configuration/app/v1/wired-networks:
    get:
      operationId: get_configuration_app_v1_wired_networks_get
      summary: Get
      description: Get a list of wired networks
      parameters:
        - name: uid
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Uid
        - name: cursor
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Cursor
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WiredNetworksResponse'
        4XX:
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - HTTPBearer: []
      tags:
        - api
        - configuration
        - v1
        - wired-networks
      x-stability-level: alpha
  /configuration/app/v1/wireless-networks:
    get:
      operationId: get_configuration_app_v1_wireless_networks_get
      summary: Get
      description: Get a list of wireless networks
      parameters:
        - name: uid
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Uid
        - name: cursor
          in: query
          required: false
          schema:
            anyOf:
              - type: string
            nullable: true
            title: Cursor
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            title: Limit
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WirelessNetworksResponse'
        4XX:
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - HTTPBearer: []
      tags:
        - api
        - configuration
        - v1
        - wireless-networks
      x-stability-level: alpha
components:
  schemas:
    ErrorDetail:
      type: object
      properties:
        message:
          type: string
          title: Message
      required:
        - message
      title: ErrorDetail
    ErrorResponse:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
          title: Detail
      required:
        - detail
      title: ErrorResponse
    GroupsGetItem:
      type: object
      properties:
        uid:
          type: string
          title: Uid
        name:
          type: string
          title: Name
        path:
          type: string
          title: Path
        parent_uid:
          anyOf:
            - type: string
          nullable: true
          title: Parent Uid
      required:
        - uid
        - name
        - path
        - parent_uid
      title: GroupsGetItem
    GroupsGetResponse:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
        groups:
          type: array
          items:
            $ref: '#/components/schemas/GroupsGetItem'
          title: Groups
      required:
        - pagination
        - groups
      title: GroupsGetResponse
    GroupsPostRequest:
      type: object
      properties:
        parent_uid:
          type: string
          title: Parent Uid
        name:
          type: string
          title: Name
      required:
        - parent_uid
        - name
      title: GroupsPostRequest
    GroupsPostResponse:
      type: object
      properties:
        parent_uid:
          type: string
          title: Parent Uid
        name:
          type: string
          title: Name
        uid:
          type: string
          title: Uid
        path:
          type: string
          title: Path
      required:
        - parent_uid
        - name
        - uid
        - path
      title: GroupsPostResponse
    PaginationDetails:
      type: object
      properties:
        limit:
          type: integer
          title: Limit
        next:
          anyOf:
            - type: string
          nullable: true
          title: Next
        previous:
          anyOf:
            - type: string
          nullable: true
          title: Previous
        first:
          anyOf:
            - type: string
          nullable: true
          title: First
        last:
          anyOf:
            - type: string
          nullable: true
          title: Last
      required:
        - limit
        - next
        - previous
        - first
        - last
      title: PaginationDetails
    SensorGroupAssignment:
      type: object
      properties:
        uid:
          type: string
          title: Uid
        group_uid:
          type: string
          title: Group Uid
        sensor_uid:
          type: string
          title: Sensor Uid
      required:
        - uid
        - group_uid
        - sensor_uid
      title: SensorGroupAssignment
    SensorGroupAssignmentsResponse:
      type: object
      properties:
        sensor_group_assignments:
          type: array
          items:
            $ref: '#/components/schemas/SensorGroupAssignment'
          title: Sensor Group Assignments
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
      required:
        - sensor_group_assignments
        - pagination
      title: SensorGroupAssignmentsResponse
    WiredNetwork:
      type: object
      properties:
        uid:
          type: string
          title: Uid
        alias:
          type: string
          title: Alias
        ip_version:
          type: string
          title: Ip Version
        sensor_count:
          type: integer
          title: Sensor Count
        updated_at:
          type: string
          format: date-time
          title: Updated At
        created_at:
          type: string
          format: date-time
          title: Created At
        disabled:
          type: boolean
          title: Disabled
        security:
          anyOf:
            - type: string
          nullable: true
          title: Security
        dns_lookup_domain:
          anyOf:
            - type: string
          nullable: true
          title: Dns Lookup Domain
        disable_edns:
          type: boolean
          title: Disable Edns
        use_dns64:
          type: boolean
          title: Use Dns64
        external_connectivity:
          type: boolean
          title: External Connectivity
        vlan_id:
          anyOf:
            - type: integer
          nullable: true
          title: Vlan Id
      required:
        - uid
        - alias
        - ip_version
        - sensor_count
        - updated_at
        - created_at
        - disabled
        - security
        - dns_lookup_domain
        - disable_edns
        - use_dns64
        - external_connectivity
        - vlan_id
      title: WiredNetwork
    WiredNetworksResponse:
      type: object
      properties:
        wired_networks:
          type: array
          items:
            $ref: '#/components/schemas/WiredNetwork'
          title: Wired Networks
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
      required:
        - wired_networks
        - pagination
      title: WiredNetworksResponse
    WirelessNetwork:
      type: object
      properties:
        uid:
          type: string
          title: Uid
        alias:
          type: string
          title: Alias
        ssid:
          type: string
          title: Ssid
        security:
          anyOf:
            - type: string
          nullable: true
          title: Security
        ip_version:
          type: string
          title: Ip Version
        sensor_count:
          type: integer
          title: Sensor Count
        updated_at:
          type: string
          format: date-time
          title: Updated At
        created_at:
          type: string
          format: date-time
          title: Created At
        disabled:
          type: boolean
          title: Disabled
        hidden:
          type: boolean
          title: Hidden
        band_locking:
          type: string
          title: Band Locking
        dns_lookup_domain:
          anyOf:
            - type: string
          nullable: true
          title: Dns Lookup Domain
        disable_edns:
          type: boolean
          title: Disable Edns
        use_dns64:
          type: boolean
          title: Use Dns64
        external_connectivity:
          type: boolean
          title: External Connectivity
      required:
        - uid
        - alias
        - ssid
        - security
        - ip_version
        - sensor_count
        - updated_at
        - created_at
        - disabled
        - hidden
        - band_locking
        - dns_lookup_domain
        - disable_edns
        - use_dns64
        - external_connectivity
      title: WirelessNetwork
    WirelessNetworksResponse:
      type: object
      properties:
        wireless_networks:
          type: array
          items:
            $ref: '#/components/schemas/WirelessNetwork'
          title: Wireless Networks
        pagination:
          $ref: '#/components/schemas/PaginationDetails'
      required:
        - wireless_networks
        - pagination
      title: WirelessNetworksResponse
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
tags:
  - name: api
  - name: v1
  - name: configuration
  - name: groups
  - name: health
  - name: sensor-group-assignments
  - name: wired-networks
  - name: wireless-networks
