openapi: 3.0.3
info:
  title: Configuration Api
  description: Nice description goes here
  termsOfService: http://we.dont.care.yet.com/term-of-service
  contact:
    name: We need a person
    url: http://we.dont.care.yet.com/contact
    email: support@capenetworks.com
  license:
    name: No idea, but we need something
  version: 1.2.0
servers:
  - url: https://api.capenetworks.com
  - url: https://api.staging.capedev.io
paths:
  /health/livez:
    get:
      operationId: get_livez_health_livez_get
      summary: Live health check
      description: Check the health of the service.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessResponse'
      deprecated: true
      tags:
        - health
  /health/readyz:
    get:
      operationId: get_readyz_health_readyz_get
      summary: Ready health check
      description: Check if the service is ready to process requests.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadinessResponse'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadinessErrorResponse'
      deprecated: true
      tags:
        - health
  /health/status:
    get:
      operationId: get_status_health_status_get
      summary: Service stats endpoint
      description: Check basic service details.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
      deprecated: true
      tags:
        - health
  /configuration/app/v1/groups:
    post:
      operationId: groups_post_configuration_app_v1_groups_post
      summary: Groups Post
      description: >-
        Create a new group with the group identified in `parent_uid` as its parent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupsPostRequest'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsPostResponse'
        4XX:
          description: Client Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        5XX:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - HTTPBearer: []
      tags:
        - api
        - configuration
        - v1
        - groups
components:
  schemas:
    ErrorDetail:
      type: object
      properties:
        message:
          type: string
          title: Message
      required:
        - message
      title: ErrorDetail
    ErrorResponse:
      type: object
      properties:
        detail:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
          title: Detail
      required:
        - detail
      title: ErrorResponse
    GroupsPostRequest:
      type: object
      properties:
        parent_uid:
          type: string
          title: Parent Uid
        name:
          type: string
          title: Name
      required:
        - parent_uid
        - name
      title: GroupsPostRequest
    GroupsPostResponse:
      type: object
      properties:
        parent_uid:
          type: string
          title: Parent Uid
        name:
          type: string
          title: Name
        uid:
          type: string
          title: Uid
        path:
          type: string
          title: Path
      required:
        - parent_uid
        - name
        - uid
        - path
      title: GroupsPostResponse
    LivenessResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - OK
          title: Status
      required:
        - status
      title: LivenessResponse
    ReadinessErrorResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: string
          title: Data
        status:
          type: string
          enum:
            - ERROR
          title: Status
      required:
        - data
        - status
      title: ReadinessErrorResponse
    ReadinessResponse:
      type: object
      properties:
        data:
          type: object
          additionalProperties:
            type: string
          title: Data
        status:
          type: string
          enum:
            - OK
          title: Status
      required:
        - data
        - status
      title: ReadinessResponse
    StatusResponse:
      type: object
      properties:
        name:
          type: string
          title: Name
        version:
          type: string
          title: Version
      required:
        - name
        - version
      title: StatusResponse
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
tags:
  - name: api
  - name: v1
  - name: configuration
  - name: groups
  - name: health
